version: "3"

services:
  cache:
    restart: always
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: --requirepass ${REDIS_PASSWORD}

  fibonacci:
    build: ./
    command:  ./fibonacci
    environment:
      - CACHE_ADDRESS=cache:${REDIS_PORT}
      - CACHE_PASSWORD=${REDIS_PASSWORD}
      - CACHE_DB_NUM=0
      - REST_PORT=${REST_PORT}
      - GRPC_PORT=${GRPC_PORT}
    ports:
      - ${REST_PORT}:${REST_PORT}
      - ${GRPC_PORT}:${GRPC_PORT}
    depends_on:
      - cache
