version: "3"

services:
  cache:
    restart: always
    image: redis
    ports:
      - 6379:6379

  fibonacci:
    build: ./
    command:  ./fibonacci
    ports:
      - 1323:1323
      - 9000:9000
    depends_on:
      - cache
